name: BrainFFA
main: fr.beyptitloup.brainffa.BrainFFAMain
version: 1.0
author: beyptitloup
description: Plugin to play at the BrainFFA
commands:
  join:
    description: Join the fight on BrainFFA
    aliases: [rejoindre, joined]
  leave:
    description: Leave the fight on BrainFFA
    aliases: [quitter, left]